import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/auth';
import { checkProjectAccess } from '@/middleware/rbac';
import { createBranch, createOrUpdateFile, createPullRequest } from '@/lib/github';
import type { StorageConfig, Project } from '@/types';

/**
 * Apply schema optimization by creating a GitHub PR with the migration (Phase 138)
 */
export async function POST(
    request: NextRequest,
    { params }: { params: Promise<{ id: string; storageId: string }> }
) {
    try {
        const session = await getSession();
        if (!session) {
            return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
        }

        const { id, storageId } = await params;
        const access = await checkProjectAccess(session.user.id, id);

        if (!access.allowed) {
            return NextResponse.json({ success: false, error: access.error }, { status: access.status });
        }

        const { project } = access as { project: Project };
        const storage = project.storageConfigs?.find((s: StorageConfig) => s.id === storageId);

        if (!storage) {
            return NextResponse.json({ success: false, error: 'Storage connector not found' }, { status: 404 });
        }

        const { recommendation, queryHash } = await request.json();
        if (!recommendation) {
            return NextResponse.json({ success: false, error: 'Recommendation is required' }, { status: 400 });
        }

        if (!project.repoFullName || !project.githubToken) {
            return NextResponse.json({ success: false, error: 'GitHub repository not connected' }, { status: 400 });
        }

        const [owner, repo] = project.repoFullName.split('/');
        const branchName = `optimize-db-${storageId.substring(0, 5)}-${Date.now().toString().substring(9)}`;
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');

        // Detect migration format based on project metadata or common patterns
        let migrationPath = '';
        let migrationContent = '';
        const framework = project.framework;

        if (recommendation.includes('CREATE INDEX')) {
            if (framework === 'nextjs' || framework === 'astro') {
                // Assume Prisma or Drizzle for these frameworks
                // In a real scenario, we'd check for directory existence
                migrationPath = `migrations/${timestamp}_optimization.sql`;
                migrationContent = `-- Optimization for query: ${queryHash}\n${recommendation}\n`;
            } else {
                migrationPath = `db/migrations/${timestamp}_optimization.sql`;
                migrationContent = `-- Optimization for query: ${queryHash}\n${recommendation}\n`;
            }
        } else if (recommendation.includes('redis.get')) {
            // Caching implementation PR
            migrationPath = `lib/cache-${storageId.substring(0, 5)}.ts`;
            migrationContent = `/**\n * Automated caching layer for ${storage.name}\n * Generated by Deployify Autonomous Database Lifecycle\n */\n\n${recommendation}\n`;
        }

        if (process.env.MOCK_DB === 'true') {
            return NextResponse.json({
                success: true,
                pullRequestUrl: `https://github.com/${owner}/${repo}/pull/mock-123`,
                branchName
            });
        }

        // Orchestrate GitHub workflow
        await createBranch(project.githubToken, owner, repo, branchName, project.defaultBranch || 'main');

        await createOrUpdateFile(
            project.githubToken,
            owner,
            repo,
            migrationPath,
            migrationContent,
            `perf: add optimized index for database ${storage.name}`,
            branchName
        );

        const isCaching = recommendation.includes('redis.get');
        const pr = await createPullRequest(
            project.githubToken,
            owner,
            repo,
            `${isCaching ? 'Cache' : 'Database'} Optimization: ${storage.name}`,
            `This PR adds ${isCaching ? 'a caching layer' : 'an optimized index'} to improve performance for the following query:\n\n\`\`\`sql\n${queryHash}\n\`\`\`\n\n**Proposed Change:**\n\`\`\`${isCaching ? 'typescript' : 'sql'}\n${recommendation}\n\`\`\`\n\nGenerated by Deployify Autonomous Database Lifecycle.`,
            branchName,
            project.defaultBranch || 'main'
        );

        return NextResponse.json({
            success: true,
            pullRequestUrl: pr.html_url,
            branchName
        });
    } catch (error) {
        console.error('[ApplyOptimizationAPI] Error:', error);
        return NextResponse.json({
            success: false,
            error: error instanceof Error ? error.message : 'Internal server error'
        }, { status: 500 });
    }
}
